services:
  postgres:
    image: postgres:16

    container_name: proxy-postgres

    restart: unless-stopped

    environment:
      POSTGRES_DB: proxydb
      POSTGRES_USER: proxy
      POSTGRES_PASSWORD: proxy

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: